(function(){
  'use strict';
  const token=localStorage.getItem('simplehpc_token')||'';
  const headers=Object.assign({'Content-Type':'application/json'},token?{Authorization:'Bearer '+token}:{});
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  async function request(url,options){const response=await fetch(url,Object.assign({cache:'no-store',headers},options||{}));const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
  async function load(){const rows=document.getElementById('aclRows');try{const data=await request('/api/v1/storage/acls');const items=data.items||[];rows.innerHTML=items.length?items.map(item=>`<tr><td>${esc(item.subject)}（${esc(item.subjectType)}）</td><td><code>${esc(item.path)}</code></td><td><span class="pill pill-success">${esc(item.permission)}</span></td><td>${esc(item.createdBy)}</td><td><button class="small-action" data-delete="${item.id}">删除</button></td></tr>`).join(''):'<tr><td colspan="5" class="api-data-missing">当前没有 ACL 授权记录</td></tr>';}catch(error){rows.innerHTML=`<tr><td colspan="5" class="api-data-missing">数据未获取：${esc(error.message)}</td></tr>`;}}
  document.addEventListener('DOMContentLoaded',function(){document.getElementById('createACL').addEventListener('click',function(){App.drawer({title:'新增目录授权',content:'<div class="_shpc-form-grid"><div class="_shpc-field"><label>对象类型</label><select id="aclType"><option value="user">用户</option><option value="group">用户组</option></select></div><div class="_shpc-field"><label>对象名称</label><input id="aclSubject"></div><div class="_shpc-field _shpc-field-wide"><label>目录绝对路径</label><input id="aclPath"></div><div class="_shpc-field"><label>权限</label><select id="aclPermission"><option value="r">只读</option><option value="rw">读写</option><option value="rwx">读写执行</option></select></div></div>',onSubmit:async function(){try{await request('/api/v1/storage/acls',{method:'POST',body:JSON.stringify({subjectType:document.getElementById('aclType').value,subject:document.getElementById('aclSubject').value,path:document.getElementById('aclPath').value,permission:document.getElementById('aclPermission').value})});await load();App.toast('ACL 已写入文件系统','success');}catch(error){App.toast(error.message,'danger');}}});});document.getElementById('aclRows').addEventListener('click',function(event){const button=event.target.closest('[data-delete]');if(!button)return;App.confirm('确认删除该 ACL？',{danger:true,onConfirm:async function(){try{await request('/api/v1/storage/acls/'+button.dataset.delete,{method:'DELETE'});await load();App.toast('ACL 已删除','success');}catch(error){App.toast(error.message,'danger');}}});});load();});
}());
